README.md

Adds a simple README that lists all NPM packages published from the repository,
None.
Not applicable, markdown only.
- Fixes #24 
N/A
N/A

Add small README to get started

---

.changeset/config.json
package.json
yarn.lock

Uses the [`@changesets/changelog-github`](https://www.npmjs.com/package/@changesets/changelog-github) plugin to beautify our `CHANGELOG.md` as described in the [changeset docs](https://github.com/changesets/changesets/blob/main/docs/config-file-options.md#changelog-false-or-a-path).
Currently, our `CHANGELOG.md` looks like this: 
> ## 3.1.3
> 
> ### Patch Changes
> 
> - 041fc926f: Add textual feedback about parsing proposal
Source: [cli/CHANGELOG.md](https://github.com/celo-org/developer-tooling/blob/master/packages/cli/CHANGELOG.md)
After this PR, the `CHANGELOG.md` will adds links to commits, include a thank-you message to the person who added the changeset, and link to the relevant PR.
For example: 
> ## 1.4.5
> 
> ### Patch Changes
> 
> - …

Updates changeset config to beautify CHANGELOG.md

---

.github/ISSUE_TEMPLATE/BUG-FORM.yml
.github/ISSUE_TEMPLATE/FEATURE-FORM.yml
.github/ISSUE_TEMPLATE/config.yml

Adds Github templates for bug reports and feature requests.
Updates template chooser, encouraging users to open Github Discussions for Q&A instead of Discord.
The Foundry repo ([foundry-rs/foundry](https://github.com/foundry-rs/foundry)) has great drop-down template for bug reports and feature requests.
This makes it a lot easier for them to review, reproduce, and fix bugs.
Our currently issue template:
* [issue-template.md](https://github.com/celo-org/developer-tooling/blob/master/.github/ISSUE_TEMPLATE/issue-template.md)
Foundry issue templates:
* [BUG-FORM.yml](https://github.com/foundry-rs/foundry/blob/master/.github/ISSUE_TEMPLATE/BUG-FORM.yml)
* [FEATURE-FORM.yml](https://github.com/foundry-rs/foundry/blob/master/.github/ISSUE_TEMPLATE/FEATURE-FORM.yml)
GitHub Docs: 
- [Syntax for …

GitHub issue templates (bug reports and feature requests link Foundry)

---

.github/workflows/containers.yml
.vscode/settings.json
packages/cli/standalone.Dockerfile

- Dockerfile for celocli (standalone) container image. This dockerfile installs celocli from npmjs registry
- GitHub Workflow for building the celocli image when a new release with name `@celo/celocli@<VERSION>` is released. If the name does not contain `@celo/celocli` it should not execute. If the release name contains `@celo/celocli` but the format does not match that (with the version) the workflow will fail. If this is intended to change (or potentially change) I can add a sanity check or we can think on a safer trigger to build the image, but considering github workflows does not have the best syntax for doing this kind of checks, if we expect the release to follow that format I'd just avoid adding syntax complexity to the workflow.
The PR configuring the required permissions is …

Celocli standalone container image

---

packages/cli/package.json
packages/cli/src/utils/cli.ts
yarn.lock

cli-table was only used by one function which itself was not used anywhere. therefore we can remove 
no 
build and tests were fine, search for function returned nil
replaces https://github.com/celo-org/developer-tooling/pull/74
yes function was unused

remove cli-table 

---

.changeset/curly-pianos-applaud.md
.changeset/plenty-bananas-shop.md
.changeset/real-rabbits-grab.md
.changeset/tough-gorillas-invent.md

Fixes small typos and improves clarity in changesets created in this PR: 
- https://github.com/celo-org/developer-tooling/pull/66
Left [comments](https://github.com/celo-org/developer-tooling/pull/66#pullrequestreview-1818582129) in #66 a couple of seconds after it was merged. This small PR applies those changes retrospectively.
No code change
- #66 
No code change

Fixes small typos and improves clarity in changesets

---

package.json
yarn.lock

tslint-plugin is for migrating, it doesnt seem we need it permanently
n/a
lint runs 
- Fixes tslint peer dep missing warning when installing
yes
n/a

remove tslint plugin for eslint

---

.github/workflows/ci.yml
dt-renovate-base.json
renovate.json

ideally we can use this config as the base for all team repos. 
* turns off automatic opening of prs -- instead we will use the dashboard to approve them to be opened. 
* for github actions the it will open prs AND will merge  them automatically if everything passes. This is safe since github actions are for ci so if ci passes the upgrade is safe. 
* sets minimum age for major version to 2 weeks to give enough time for big bugs to be sorted out. and 4 days for minor and patch which is typically enough for evil hijack type updates to be found and removed. 
*  set max concurrent prs to 2. each pr that is open will rebase automatically on each merge so having more open just creates noise and actually slows down the merge process.
add the same renovate validate ci step used on faucet repo
- …

set up base config for renovate on developer tooling repos

---

package.json
yarn.lock

@soloseng  noticed that monorepo was using wrong fork of ganache and fixed on monorepo  https://github.com/celo-org/celo-monorepo/pull/10917 this does the same here
n/a
- parrallel to https://github.com/celo-org/celo-monorepo/pull/10917
yep
_Brief explanation of why these changes are/are not backwards compatible._

use celo verison of ganache (rather than random soloseng version)

---

packages/cli/src/commands/exchange/celo.ts
packages/cli/src/exchange-stable-base.ts
packages/cli/src/utils/exchange.ts

When performing a swap that would significantly alter the price (de-peg) be sure to check the absolute difference (-25% is just as bad as 25%) 
make warning more concise (saying that 24% is greater than 20% is not really useful)

Big Swap Feedback

---

.github/workflows/release.yaml

fixes "branch not valid" error when release flow is ran

default is master

---

CONTRIBUTING.md

Fixes URL typo in CONTRIBUTING
N/A, docs-only change
N/A
Yes, docs-only change.
Yes, it's a docs change.

Nit: Fixes URL typo in CONTRIBUTING

---

.changeset/spotty-brooms-itch.md

npm is inconsistent on if beta 2 was published so go for beta 3 
running `npm view` shows beta 1 as last published but when trying to publish beta 2 is shown is already published. Usually the best fix for this is just to increment the version which adding a changeset should do

version bump for cli beta

---

.changeset/happy-rice-camp.md
packages/cli/src/commands/election/activate.ts
packages/docs/sdk/docs/contractkit/classes/wrappers_Election.ElectionWrapper.md
packages/docs/sdk/docs/contractkit/modules/wrappers_Election.md
packages/sdk/contractkit/src/wrappers/Election.ts

New `--for` parameter and matching plumbing in ContractKit to allow pending votes to be activated from any account, not just from msg.sender. 
```
packages/cli/bin/run.js election:activate --help
Activate pending votes in validator elections to begin earning rewards. To earn rewards as a voter, it is required to activate your pending votes at some point after the end of the epoch in which they were made.
USAGE
$ celocli election:activate --from <value> [--globalHelp] [--for <value>] [--wait]
FLAGS
--for=0xc1912fEE45d61C87Cc5EA59DaE31190FFFFf232d   Optional: use this to activate votes for another address
--from=0xc1912fEE45d61C87Cc5EA59DaE31190FFFFf232d  (required) Address sending transaction (and voter's address if --for not specified)
--globalHelp …
```

Activate votes from any account 

---

packages/docs/sdk/docs/connect/README.md
packages/sdk/connect/README.md

Fixes the code example in the `@celo/connect` README.
```diff
const web3 = new Web3("YOUR_RPC_URL")
const connection = new Connection(web3)
- connection.setProvider()
```
`connection.setProvider()` doesn't need to be called explicitly with a `CeloProvider`, because `connection` is already configured with a `CeloProvider` in the constructor:
https://github.com/celo-org/developer-tooling/blob/0ad9c011b868c4bf5456f4048cb6d405c9dd8c8e/packages/sdk/connect/src/connection.ts#L77-L93
Docs only change
Yes
Yes

Fix @celo/connect README code example

---

.changeset/two-poems-complain.md
packages/cli/package.json
packages/cli/src/commands/exchange/celo.ts
packages/cli/src/commands/lockedgold/withdraw.ts
packages/cli/src/commands/releasecelo/transfer-dollars.ts
packages/cli/src/commands/releasecelo/withdraw.test.ts
packages/cli/src/commands/releasecelo/withdraw.ts
packages/cli/src/commands/transfer/celo.test.ts
packages/cli/src/commands/transfer/celo.ts
packages/cli/src/commands/transfer/dollars.test.ts
packages/cli/src/commands/transfer/erc20.ts
packages/cli/src/commands/transfer/euros.test.ts
packages/cli/src/exchange-stable-base.ts
packages/cli/src/transfer-stable-base.ts
packages/cli/src/utils/checks.ts
packages/cli/src/utils/helpers.ts
yarn.lock

Adds the @celo/compliance package to ensure commands which transfer tokens do not work with OFAC sanctioned addresses. 
As transfer commands did not have tests this adds tests for basic case and for non compliant case.
New Tests. 
- Fixes #145 
yep
n/a

Compliance + Test

---

README.md
packages/cli/README.md
packages/docs/sdk/docs/connect/README.md
packages/docs/sdk/docs/contractkit/README.md
packages/docs/sdk/docs/cryptographic-utils/README.md
packages/docs/sdk/docs/phone-utils/README.md
packages/sdk/base/README.MD
packages/sdk/connect/README.md
packages/sdk/contractkit/README.md
packages/sdk/cryptographic-utils/README.md
packages/sdk/explorer/README.md
packages/sdk/governance/README.md
packages/sdk/keystores/README.md
packages/sdk/network-utils/README.md
packages/sdk/phone-utils/README.md
packages/sdk/transactions-uri/README.md
packages/sdk/utils/README.md
packages/sdk/wallets/wallet-base/Readme.md
packages/sdk/wallets/wallet-hsm-aws/README.MD
packages/sdk/wallets/wallet-hsm-azure/README.md
packages/sdk/wallets/wallet-hsm-gcp/README.md
packages/sdk/wallets/wallet-hsm/README.md
packages/sdk/wallets/wallet-ledger/README.MD
packages/sdk/wallets/wallet-local/Readme.MD
packages/sdk/wallets/wallet-remote/README.md
packages/sdk/wallets/wallet-rpc/README.md

Adds "how we work" section in various READMEs. 
Based on [feedback](https://clabsco.slack.com/archives/C014SRL4URY/p1708973042787839?thread_ts=1708971223.840439&cid=C014SRL4URY) from the Celo Foundation and external contributors, it's not clear how to reach us.  
My goal with this PR is to be (particularly) explicit that we have a strong preference for GitHub.
My goal is to display this information on npmjs.org (for each package) and celo.docs.org, which is where most of our users interface with our products. I hypothesize that most folks don't know that [celo-org/developer-tooling](https://github.com/celo-org/developer-tooling) is where we work and encourage communication.
Docs-only changes
N/A
Yes, docs-only change
Yes, docs change

Adds "how we work" section across READMEs

---

packages/cli/src/commands/lockedgold/lock.test.ts
packages/cli/src/commands/lockedgold/unlock.test.ts
packages/cli/src/commands/lockedgold/update-delegated-amount.test.ts
packages/cli/src/commands/releasecelo/locked-gold.test.ts
packages/cli/src/test-utils/cliUtils.ts

Fix 'Jest did not exit one second after the test run has completed.This usually means that there are asynchronous operations that weren't stopped in your tests.'
n/a
ran locally

Fix Jest Long Test Timeouts

---

packages/cli/src/commands/election/list.test.ts

This PR adds a test for `election:test` command. It takes no params as such, so only one case is tested.
None.
Ran tests.
#141 
None.

election:list tests

---

packages/cli/src/commands/election/revoke.test.ts
packages/cli/src/test-utils/chain-setup.ts

This PR adds a test for `election:revoke` command.
None.
Ran tests.
#141 
None.

election:revoke tests

---

packages/cli/src/commands/election/activate.test.ts
packages/cli/src/commands/election/revoke.test.ts
packages/cli/src/commands/election/vote.test.ts
packages/cli/src/test-utils/cliUtils.ts

This PR adds a test for `election:vote` command.
None.
Ran tests.
#141 
None.

election:vote tests

---

packages/cli/src/commands/election/activate.test.ts

This PR extends `election:activate` tests to include `--wait` flag coverage.
None.
Ran tests.
#141 
None.

case for election:activate --wait

---

packages/cli/src/commands/election/current.test.ts

This PR adds a test for `election:current` command.
None.
Ran tests.
Fixes #141 
None.

election:current tests

---

dt-renovate-base.json

https://docs.renovatebot.com/configuration-options/#rangestrategy
This is inresponse to renovate commits like https://github.com/celo-org/developer-tooling/commit/cbfedf0849a69e347a6ee3647b301ca0e7a11cac which only updated the yarn lock which isnt good for us as we are publishing libraries

Enforce Package dep version bump

---

.changeset/quick-tips-happen.md
packages/docs/sdk/docs/connect/interfaces/types.EncodedTransaction.md
packages/docs/sdk/docs/connect/interfaces/types.Error.md
packages/docs/sdk/docs/connect/interfaces/types.EthereumLegacyTXProperties.md
packages/docs/sdk/docs/connect/interfaces/types.HttpProvider.md
packages/docs/sdk/docs/connect/interfaces/types.JsonRpcPayload.md
packages/docs/sdk/docs/connect/interfaces/types.JsonRpcResponse.md
packages/docs/sdk/docs/connect/interfaces/types.Provider.md
packages/docs/sdk/docs/connect/interfaces/types.RLPEncodedTx.md
packages/docs/sdk/docs/connect/modules/index.md
packages/docs/sdk/docs/connect/modules/types.md
packages/docs/sdk/docs/wallet-base/classes/wallet_base.WalletBase.md
packages/docs/sdk/docs/wallet-base/modules/signing_utils.md
packages/sdk/connect/src/types.ts
packages/sdk/wallets/wallet-base/src/signing-utils.test.ts
packages/sdk/wallets/wallet-base/src/signing-utils.ts
packages/sdk/wallets/wallet-base/src/wallet-base.ts

Celo legacy Type 0 transactions were deprecated in the Gingerbread hardfork. As a first step, transactions that don't require alternative fee currencies should fallback to Ethereum-compatible TXs that are still supported.
Fixed a typo in the check.
Added tests.
Yes.

Added Ethereum-compatible legacy TXs support

---

.vscode/extensions.json
.vscode/settings.json

vs code keeps recommending to install this deprecated extension. so lets not do that

remove outdated extensions from recs

---

.changeset/eight-dragons-behave.md
.changeset/khaki-lies-wait.md
packages/cli/src/base.ts
packages/cli/src/commands/config/set.test.ts
packages/cli/src/commands/config/set.ts
packages/cli/src/transfer-stable-base.ts
packages/cli/src/utils/command.ts
packages/cli/src/utils/config.test.ts
packages/cli/src/utils/config.ts

Following the discussion we had, this:
- ignores --gasCurrency when passed to `config:set` but prints a warning linking to a discussion
- change `StrongAddress | 'CELO'` type to `StrongAddress` as `CELO` is the default if no flag is passed
- adds a test for `config:set`
- fix `packages/cli/src/transfer-stable-base.ts` to use the kit.connection.defaultFeeCurrency instead of reimplementing the same logic as `packages/cli/src/base.ts`

feat: ignores gasCurrency when passed to the config

---

.changeset/early-geckos-rescue.md
packages/cli/src/commands/lockedgold/lock.test.ts
packages/cli/src/commands/lockedgold/lock.ts

Rather than failing of EOA is not registered with Account contract, just do the registration
simplify the process of voting by registering eoa as given that account is often used a synonym for eoa it was not clear from error messages that one must run account:register. this way it happens automatically for a nicer ux
This is slightly different than plan specified in #142 which was to register and lock while voting. but i think now that locking and voting in same might be a bit much
n/a
add new test
- Fixes #142
yes
n/a

Automatically register account if needed when locking

---

.github/workflows/open-docs-pr.yml
packages/cli/bin/run.js
packages/cli/tsconfig.json
packages/docs/command-line-interface/account.md
packages/docs/command-line-interface/config.md
packages/docs/command-line-interface/dkg.md
packages/docs/command-line-interface/election.md
packages/docs/command-line-interface/exchange.md
packages/docs/command-line-interface/governance.md
packages/docs/command-line-interface/grandamento.md
packages/docs/command-line-interface/identity.md
packages/docs/command-line-interface/lockedgold.md
packages/docs/command-line-interface/multisig.md
packages/docs/command-line-interface/network.md
packages/docs/command-line-interface/node.md
packages/docs/command-line-interface/oracle.md
packages/docs/command-line-interface/releasecelo.md
packages/docs/command-line-interface/reserve.md
packages/docs/command-line-interface/rewards.md
packages/docs/command-line-interface/transfer.md
packages/docs/command-line-interface/utils.md
packages/docs/command-line-interface/validator.md
packages/docs/command-line-interface/validatorgroup.md
packages/sdk/wallets/wallet-base/src/signing-utils.ts

This PR has the following fixes:
- [CI] uses a `cp` command rather than the postinstall hook of the target repository (docs) because it includes more logic (such as `git submodules update` which defeated the docs gh action)
- [CLI docs] fixes the entrypoint to not use `await import` but good ol' `require` so oclif can generate the docs

docs ci: manually copy the files rather than use the postinstall hook
